mod activity1;
mod activity2;
mod basics;
mod activity3a;
mod activity3b;
mod activity4a;
mod activity4b;
mod activity5;
mod activity6;
mod activity7;
mod activity8;
mod activity9;
mod activity10;
mod activity11;
mod activity12;
mod activity13;
mod activity14;
mod activity15;
mod activity16;
mod activity17;
mod activity18a;
mod activity18b;
mod activity19;

pub fn main() {
    basics::run();
    activity1::run();
    activity2::run();
    activity3a::run();
    activity3b::run();
    activity4a::run();
    activity4b::run();
    activity5::run();
    activity6::run();
    activity7::run();
    activity8::run();
    activity9::run();
    activity10::run();
    activity11::run();
    activity12::run();
    activity13::run();
    activity14::run();
    activity15::run();
    activity16::run();
    activity17::run();
    activity18a::run();
    activity18b::run();
    activity19::run();
}
